import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

        public static void main(String[] args) {
            Scanner scn = new Scanner(System.in);
            Player player = new Player();

            SIPlayer computer = new SIPlayer();

            while(player.getPlayerOcean().checkBoard() > 0 || computer.getOcean().checkBoard() > 0){
                System.out.println("Your turn try to blast computer ship:");
                System.out.println("Enter X coordinate: ");
                int x = scn.nextInt();
                System.out.println("Enter Y coordinate: ");
                int y = scn.nextInt();
                computer.getOcean().blastShip(x,y);
                System.out.println("Computers TURN");
                computer.computerShoot(player.getPlayerOcean());
                if(computer.getOcean().checkBoard() == 0){
                    System.out.println("You win!");
                    return;
                } else if(player.getPlayerOcean().checkBoard() == 0){
                    System.out.println("Computer wins");
                    return;
                }


            }

        }


}
