/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    public static void main(String[] args) {
        Ocean board = new Ocean();
        board.setShip(3,4);
        board.printBoard();
        board.blastShip(3,2);


        board.blastShip(3,4);
        board.printBoard();
        SIPlayer si = new SIPlayer();

        for(int i = 0; i < 5; i++){

        }

        si.setComputerShips();

        Player player = new Player();

    }
}
